# Generated by Django 3.1.1 on 2021-02-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='icon',
            field=models.ImageField(blank=True, help_text='Group icon', upload_to='chartgroup_icons'),
        ),
    ]
